### ISSUE TITLE
New LV2 compilation from master throwing errors

### ISSUE THREAD

**Issue by REIS0** [kushview/roboverb#14]
After talking in #12 and seeing updates in master branch I've decided to recompile it from scratch, since we're not dealing with libjuce anymore I thought a new issue would be better. If we should move to the older one just tell me!

After cloning from master and trying to compile I'm getting this error
```
[4/5] Compiling roboverb.lv2/roboverb.ttl.in
In file included from ../roboverb.lv2/Plugin.cpp:20:
../libs/lvtk/lvtk/plugin.hpp: In instantiation of ‘void lvtk::Descriptor<P>::register_plugin(const char*) [with P = Module]’:
../libs/lvtk/lvtk/plugin.hpp:85:9:   required from ‘lvtk::Descriptor<P>::Descriptor(const char*) [with P = Module]’
../roboverb.lv2/Plugin.cpp:134:61:   required from here
../libs/lvtk/lvtk/plugin.hpp:94:29: error: invalid conversion from ‘void* (*)(const lvtk::_LV2_Descriptor*, double, const char*, const LV2_Feature* const*)’ to ‘void* (*)(const LV2_Descriptor*, double, const char*, const LV2_Feature* const*)’ [-fpermissive]
   94 |         desc.instantiate    = P::_instantiate;
      |         ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
      |                             |
      |                             void* (*)(const lvtk::_LV2_Descriptor*, double, const char*, const LV2_Feature* const*)

Waf: Leaving directory `/home/arthur/Dev/Git/Roboverb/build'
Build failed
 -> task in 'roboverb' failed with exit status 1:
	{task 140032145632592: cxx Plugin.cpp -> Plugin.cpp.3.o}
['/usr/bin/g++', '-Os', '-std=c++17', '-Wno-deprecated-declarations', '-fvisibility=hidden', '-fPIC', '-Iroboverb.lv2', '-I../roboverb.lv2', '-Iroboverb.lv2/compat', '-I../roboverb.lv2/compat', '-Ilibs/lvtk', '-I../libs/lvtk', '-DNDEBUG=1', '-DLINUX=1', '-DHAVE_LV2=1', '../roboverb.lv2/Plugin.cpp', '-c', '-o/home/arthur/Dev/Git/Roboverb/build/roboverb.lv2/Plugin.cpp.3.o']
```
I've tried cleaning and checking for something in my system and I got this error every time. I'm currently running Pop_OS 20.10 and as said before compiling from the current master branch.

**Comment by mfisher31** [comment]
Submodule for LVTK might be out of date. `git submodule update --init`

**Comment by REIS0** [comment]
Using `git submodule update --init --recursive `, and `git submodule update --init` didn't worked, got the same error. But your answer is right, I just had to manually go in the `lvtk` subdirectory and do a `git pull origin master`. 

EDIT: Just to know, when using `git submodule update --init --recursive` the `lvtk` is cloned from commit `47fd781`, but the commit that compiles is `8608628`.

**Comment by mfisher31** [comment]
Ok, thanks for the info.  I'll get in there and make sure it pulls the right revision on a fresh clone.
