### ISSUE TITLE
LV2 version no sound in Ardour

### ISSUE THREAD

**Issue by REIS0** [kushview/roboverb#16]
Here I am with another issue! Jokes aside I've decided to finally test it in ardour and basically it don't work, when active the plugin actually mutes the audio, the impression it gives is that the generated samples in the plugin are not being sent to the audio output.

1. Open an ardour session
2. Add a midi track
3. Add roboverb lv2 after the sound source (synth plugin or whatever, in my case I've used surge)
4. When roboverb is active there's no sound, bypass it and sound is back

As before I'm using Pop_OS! 20.10, Ardour 6.6 running JACK with 96k and 1024 as buffer, I can't test if It's a bug with the sampling rate because my motherboard soundcard basically don't allow me to use anything below 96k, so I can only ask to also test this. Here's a [video](https://www.youtube.com/watch?v=hsULVtEONBM) showing the problem.

**Comment by mfisher31** [comment]
Thanks for the update.

**Comment by mfisher31** [comment]
https://gitlab.com/kushview/Roboverb/-/issues/16
